"""Add id column to contract_additional_files

Revision ID: 2b8b469977d0
Revises: d37483fbfd43
Create Date: 2025-06-07 12:03:45.212234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8b469977d0'
down_revision = 'd37483fbfd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_additional_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_additional_files', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
