"""Add unit and price_with_vat to WorkType

Revision ID: 43fa26595b36
Revises: 9dc158cbe837
Create Date: 2025-05-30 16:01:01.544001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fa26595b36'
down_revision = '9dc158cbe837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('price_with_vat', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_types', schema=None) as batch_op:
        batch_op.drop_column('price_with_vat')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
