"""Add WorkType and many-to-many relationship

Revision ID: 9dc158cbe837
Revises: 65e3da171252
Create Date: 2025-05-27 22:52:37.132927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc158cbe837'
down_revision = '65e3da171252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contract_work_types',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('work_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'work_type_id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('work_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_description', sa.TEXT(), autoincrement=False, nullable=False))

    op.drop_table('contract_work_types')
    op.drop_table('work_types')
    # ### end Alembic commands ###
