"""Добавление поля object_name и таблиц для вложений

Revision ID: d37483fbfd43
Revises: 0322fb214fe4
Create Date: 2025-06-06 20:21:18.290356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37483fbfd43'
down_revision = '0322fb214fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_additional_files',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_table('contract_documents',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('object_name')

    op.drop_table('contract_documents')
    op.drop_table('contract_additional_files')
    # ### end Alembic commands ###
